In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [4]:
df = pd.read_csv("Mall_Customers.csv")

df.head()

,CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100)
0,1,Male,19,15,39
1,2,Male,21,15,81
2,3,Female,20,16,6
3,4,Female,23,16,77
4,5,Female,31,17,40


In [5]:
df = df.drop("CustomerID", axis=1)

In [6]:
df["Gender"] = df["Gender"].map({"Male": 0, "Female": 1})

In [7]:
X = df.values

In [8]:
kmeans_no_scale = KMeans(n_clusters=5, random_state=42)

y_no_scale = kmeans_no_scale.fit_predict(X)

In [9]:
print(kmeans_no_scale.cluster_centers_)

[[  0.61797753  46.21348315  47.71910112  41.79775281]
 [  0.54545455  32.45454545 108.18181818  82.72727273]
 [  0.51724138  24.68965517  29.5862069   73.65517241]
 [  0.47368421  40.39473684  87.          18.63157895]
 [  0.54545455  31.78787879  76.09090909  77.75757576]]


In [10]:
X_scaled = df.copy()

age_column = X_scaled["Age"]

In [ ]:
scaler = StandardScaler()

X_scaled[["Gender", "Annual Income (k$)", "Spending Score (1-100)"]] = \
scaler.fit_transform(
    X_scaled[["Gender", "Annual Income (k$)", "Spending Score (1-100)"]]
)

X_scaled["Age"] = age_column

In [12]:
X_scaled = X_scaled.values

In [13]:
kmeans_scaled = KMeans(n_clusters=5, random_state=42)

y_scaled = kmeans_scaled.fit_predict(X_scaled)

In [14]:
print(kmeans_scaled.cluster_centers_)

[[-4.08667360e-01  6.35357143e+01 -2.96740048e-01 -4.54212260e-01]
 [ 1.56996543e-01  3.12586207e+01  3.03065268e-01  5.66527051e-01]
 [-1.20873445e-01  2.14000000e+01 -5.44296060e-01  1.83431874e-01]
 [ 1.98507608e-01  4.94390244e+01 -5.58204628e-02 -5.22860142e-01]
 [-2.93026532e-02  3.92424242e+01  4.48224763e-01 -1.83049541e-01]]
