In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [3]:
data = {
'vehicle_serial_no': [5, 3, 8, 2, 4, 7, 6, 10, 1, 9],
'mileage': [150000, 120000, 250000, 80000, 100000, 220000, 180000, 300000, 75000, 280000],
'fuel_efficiency': [15, 18, 10, 22, 20, 12, 16, 8, 24, 9],
'maintenance_cost': [5000, 4000, 7000, 2000, 3000, 6500, 5500, 8000, 1500, 7500],
'vehicle_type': ['SUV','Sedan','Truck','Hatchback','Sedan','Truck','SUV','Truck','Hatchback','SUV']
}

df = pd.DataFrame(data)

df.head()

,vehicle_serial_no,mileage,fuel_efficiency,maintenance_cost,vehicle_type
0,5,150000,15,5000,SUV
1,3,120000,18,4000,Sedan
2,8,250000,10,7000,Truck
3,2,80000,22,2000,Hatchback
4,4,100000,20,3000,Sedan


In [4]:
df = df.drop("vehicle_serial_no", axis=1)

In [5]:
df["vehicle_type"] = df["vehicle_type"].map({
    "SUV":0,
    "Sedan":1,
    "Truck":2,
    "Hatchback":3
})

In [6]:
X = df.values

In [7]:
kmeans_no_scale = KMeans(n_clusters=3, random_state=42)

y_no_scale = kmeans_no_scale.fit_predict(X)

print("Cluster centers without scaling:")
print(kmeans_no_scale.cluster_centers_)

Cluster centers without scaling:
[[8.50000000e+04 2.20000000e+01 2.16666667e+03 2.33333333e+00]
 [2.62500000e+05 9.75000000e+00 7.25000000e+03 1.50000000e+00]
 [1.50000000e+05 1.63333333e+01 4.83333333e+03 3.33333333e-01]]


In [8]:
df_scaled = df.copy()

vehicle_type_col = df_scaled["vehicle_type"]

In [ ]:
scaler = StandardScaler()

df_scaled[["mileage","fuel_efficiency","maintenance_cost"]] = \
scaler.fit_transform(
    df_scaled[["mileage","fuel_efficiency","maintenance_cost"]]
)

df_scaled["vehicle_type"] = vehicle_type_col

In [10]:
X_scaled = df_scaled.values

kmeans_scaled = KMeans(n_clusters=3, random_state=42)

y_scaled = kmeans_scaled.fit_predict(X_scaled)

print("Cluster centers with scaling:")
print(kmeans_scaled.cluster_centers_)

Cluster centers with scaling:
[[-1.23839981  1.43014887 -1.48341526  3.        ]
 [ 1.09939575 -1.06320278  1.0269798   1.5       ]
 [-0.48019584  0.34812834 -0.28527217  0.5       ]]


In [11]:
print("Without scaling:", y_no_scale)
print("With scaling:", y_scaled)

Without scaling: [2 2 1 0 0 1 2 1 0 1]
With scaling: [2 2 1 0 2 1 2 1 0 1]
